---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Serverske aplikacije na mrezi"
subtitle: "QNAP TS-251+, VM server"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  #style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #title: "Demo !"
  #icon: "fa fa-grin"
  #content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
#  - name: "another page!"
#    icon: "fas fa-file-alt"
#    url: "#additionnal-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Aplikacije"
    icon: "fas fa-sitemap"
    items:
      - name: "Uni-Fi"
        logo: "assets/icons/unifi-icon.png"
        subtitle: "Uni-Fi controller"
        tag: "app"
        url: "https://192.168.22.239:8443"
        target: "_blank" # optional html a tag target attribute
      - name: "LibreNMS"
        logo: "assets/icons/librenms-icon.png"
        subtitle: "LibreNMS network monitoring system"
        tag: "app"
        url: "http://192.168.22.241"
        target: "_blank"
      - name: "phpVirtualBox"
        logo: "assets/icons/virtualboxvbox-icon.png"
        subtitle: "phpVirtualBox server web interfejs"
        tag: "app"
        url: "http://192.168.22.240/phpvirtualbox"
        target: "_blank"
      - name: "apt-cacher"
        logo: "assets/tools/sample.png"
        subtitle: "apt proxy network cacher"
        tag: "app"
        url: "http://192.168.22.235:3142/acng-report.html"
        target: "_blank"
  - name: "Aplikacije na Qnapu"
    icon: "fas fa-tasks"
    items:
      - name: "Plex"
        logo: "assets/icons/plex-icon.png"
        subtitle: "lokalno strimovanje filmova i serija"
        tag: "app"
        url: "http://192.168.22.200:32400"
        target: "_blank"
      - name: "Jackett"
        logo: "assets/icons/jacket-icon.png"
        subtitle: "Jaclett indexer"
        tag: "app"
        url: "http://192.168.22.200:9117"
        target: "_blank" # optional html a tag target attribute
      - name: "Radarr"
        logo: "assets/icons/radarr-icon.png"
        subtitle: "automatsko skidanje filmova"
        tag: "app"
        url: "http://192.168.22.200:7878"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/icons/sonarr-icon.png"
        subtitle: "automatasko skidanje serija"
        tag: "app"
        url: "http://192.168.22.200:8989"
        target: "_blank"
      - name: "Bazarr"
        logo: "assets/icons/bazarr-icon.png"
        subtitle: "automatsko skidanje prevoda za filmove i serije"
        tag: "app"
        url: "http://192.168.22.200:6767"
        target: "_blank"
      - name: "Transmission"
        logo: "assets/icons/transmission-icon.png"
        subtitle: "torrent downloader"
        tag: "app"
        url: "http://192.168.22.200:9091/transmission/web/"
        target: "_blank"
      - name: "Double Commander"
        logo: "assets/icons/doublecommander-icon.png"
        subtitle: "Total commander, samo drugacije"
        tag: "app"
        url: "http://192.168.22.200:3000"
        target: "_blank"
      - name: "Midnight Commander"
        logo: "assets/icons/mc-icon.png"
        subtitle: "Total commander, samo drugacije"
        tag: "app"
        url: "http://192.168.22.200:18888"
        target: "_blank"
  - name: "Webmins"
    icon: "far fa-folder"
    items:
      - name: "Webmin VM"
        logo: "assets/icons/webmin-icon.png"
        subtitle: "Webmin na Vm serveru"
        tag: "webmin"
        url: "https://192.168.22.240:10000"
        target: "_blank" # optional html a tag target attribute
      - name: "Webmin LibreNMS"
        logo: "assets/icons/webmin-icon.png"
        subtitle: "Webmin na LibreNMS serveru"
        tag: "webmin"
        url: "https://192.168.22.241:10000"
        target: "_blank"
      - name: "Webmin Pi-hole"
        logo: "assets/icons/webmin-icon.png"
        subtitle: "Webmin na Pi-hole serveru"
        tag: "webmin"
        url: "http://192.168.22.230:10000"
        target: "_blank"
  - name: "Portainers"
    icon: "fab fa-megaport"
    items:
      - name: "Portainer QNAP"
        logo: "assets/icons/portainer-icon.png"
        subtitle: "portainer na Qnap serveru"
        tag: "portainer"
        url: "http://192.168.22.200:9000"
        target: "_blank" # optional html a tag target attribute
      - name: "Portainer VM"
        logo: "assets/icons/portainer-icon.png"
        subtitle: "portainer na VM serveru"
        tag: "portainer"
        url: "http://192.168.22.240:9100"
        target: "_blank"
  - name: "Pi-holes"
    icon: "far fa-circle"
    items:
      - name: "Pi-hole"
        logo: "assets/icons/pi-hole-icon.png"
        subtitle: "Pi-hole na Raspberry Pi serveru"
        tag: "portainer"
        url: "http://192.168.22.230/admin/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pi-hole"
        logo: "assets/icons/pi-hole-icon.png"
        subtitle: "Pi-hole na VM serveru"
        tag: "portainer"
        url: "http://192.168.22.240:1010/admin/"
        target: "_blank"
  - name: "Qnap"
    icon: "fas fa-server"
    items:
      - name: "TS-251+"
        logo: "assets/icons/ts-251+.png"
        subtitle: "Qnap TS-251+ server"
        tag: "server"
        url: "https://192.168.22.200"
        target: "_blank" # optional html a tag target attribute
      - name: "TS"
        logo: "assets/tools/sample2.png"
        subtitle: "Qnap ---"
        tag: "server"
        url: "http://xxx/"
        target: "_blank"